name: Docker Package Download

on:
  workflow_dispatch:

jobs:
  entry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4

      - name: Show current ref
        run: |
          echo "github.ref = ${{ github.ref }}"
          echo "github.sha = ${{ github.sha }}"
